[package]
name = "quizface"
version = "0.1.1"
authors = ["zingolabs"]
edition = "2018"
default-run="quizface"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
regex = "*"
