name: cargo-test-quizface

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name:  Authenticate Github CR
      env: 
        PAT: ${{ secrets.CONTAINER_REGESTRY_READ }}
      run: echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
    - name: Pull image
      run: docker pull ghcr.io/zingolabs/zcashrpc:latest
    - name: Run Tests
      run:  docker run  -v /home/runner/work/quizface/quizface:/quizface ghcr.io/zingolabs/zcashrpc:latest bash -c "./zcash/src/zcashd -daemon && cd quizface && cargo test"
